spring:
  main:
    banner-mode: off
  application:
    name: holder

  server:
    port: ${SERVER_PORT:8080}

  datasource:
    url: jdbc:postgresql://localhost:5432/holder
    username: app_holder
    password: app_holder
    driver-class-name: org.postgresql.Driver

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: public
    default-schema: public

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  cloud:
    openfeign:
      client:
        decodeSlash: false
        config:
          default:
            logger-level: full
            connect-timeout: 30000
            read-timeout: 30000
      okhttp:
        enabled: true
      httpclient:
        ok-http:
          read-timeout: 30000

  logging:
    level:
      org:
        springframework:
          web: DEBUG
      com:
        montebruni:
          holder: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  providers:
    brapi:
      host: ${BRAPI_HOST:https://brapi.dev}
      token: ${BRAPI_TOKEN:123123}
      retry:
        initial-await-time-ms: 1000
        max-await-time-ms: 10000
        attempts: 3
  url:
    recover-password: ${RECOVER_PASSWORD_URL:http://localhost:${spring.server.port}/recover-password?token=}
